default_chain: stride-testnet
chains:
  gaia-testnet:
    key: troponCwallet
    chain-id: GAIA
    rpc-addr: http://159.223.3.144:23657      
    grpc-addr: http://159.223.3.144:23090     
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride-testnet:
    key: troponCwallet
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://127.0.0.1:16657      
    grpc-addr: http://0.0.0.0:16090     
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
